server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-productos
          uri: lb://MS-PRODUCTOS
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=2
        - id: ms-facturacion
          uri: lb://MS-FACTURACION
          predicates:
            - Path=/api/facturacion/**
          filters:
            - StripPrefix=2
        - id: ms-stock
          uri: lb://MS-STOCK
          predicates:
            - Path=/api/stock/**
          filters:
            - StripPrefix=2

