server:
  port: 8081

spring:
  application:
    name: MS-PRODUCTOS

  datasource:
    url: jdbc:mysql://localhost:3306/nombreadefiniraunchi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

gateway:
  internal-secret: "Sabri67Mayra127Solange6Camila9"
